package com.ai_interview_platform.Services.Imp;

import com.ai_interview_platform.DTOs.CompleteInterviewRequest;
import com.ai_interview_platform.DTOs.ScorecardResponse;
import com.ai_interview_platform.Models.InterviewSession;
import com.ai_interview_platform.Models.InterviewStatus;
import com.ai_interview_platform.Models.Scorecard;
import com.ai_interview_platform.Repositories.InterviewSessionRepository;
import com.ai_interview_platform.Repositories.ScorecardRepository;
import com.ai_interview_platform.Services.ScorecardService;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.UUID;
@Service
@RequiredArgsConstructor
public class ScorecardServiceImp implements ScorecardService {

    private final InterviewSessionRepository interviewSessionRepository;
    private final ScorecardRepository scorecardRepository;

    @Override
    public ScorecardResponse completeInterview(UUID sessionId, CompleteInterviewRequest request) {

        InterviewSession session = interviewSessionRepository.findById(sessionId).orElseThrow(
                () -> new IllegalArgumentException("Interview Session Not Found")
        );
        if (session.getStatus() != InterviewStatus.IN_PROCESS) {
            throw new IllegalArgumentException("Only in-progress interview can be  completed");
        }

        if (scorecardRepository.findBySession(session).isPresent()) {
            throw new IllegalArgumentException("interview is already  completed");
        }

        int overallScore = (request.technicalScore()
                + request.communicationScore()
                + request.problemSolvingScore()) / 3;

        Scorecard scorecard = Scorecard.builder()
                .session(session)
                .technicalScore(request.technicalScore())
                .communicationScore(request.communicationScore())
                .problemSolvingScore(request.problemSolvingScore())
                .overallScore(overallScore)
                .strengths("Evaluation will be generated by AI.")
                .weaknesses("Evaluation will be generated by AI.")
                .feedback("Evaluation will be generated by AI.")
                .createdAt(LocalDateTime.now())
                .build();

        Scorecard save = scorecardRepository.save(scorecard);
        session.setStatus(InterviewStatus.COMPLETED);
        session.setCompletedAt(LocalDateTime.now());

        interviewSessionRepository.save(session);

        return mapToResponse(save);

    }

    private ScorecardResponse mapToResponse(Scorecard scorecard) {
        return new ScorecardResponse(
                scorecard.getId(),
                scorecard.getSession().getId(),
                scorecard.getTechnicalScore(),
                scorecard.getProblemSolvingScore(),
                scorecard.getOverallScore(),
                scorecard.getStrengths(),
                scorecard.getWeaknesses(),
                scorecard.getFeedback(),
                scorecard.getCreatedAt()

        );
    }

    @Override
    @Transactional(readOnly = true)
    public ScorecardResponse getScorecard(UUID sessionId) {

        InterviewSession session = interviewSessionRepository.findById(sessionId).orElseThrow(()->
                new IllegalArgumentException("Interview Session Not Found"));

        Scorecard scorecard= scorecardRepository.findBySession(session).orElseThrow(()->
                new IllegalArgumentException("Scorecard Not Found"));

        return mapToResponse(scorecard);

    }



}
